package com.acme.hormonalcare.backend.medicalRecord.domain.model.valueobjects;

public enum SubSpecialties {
    DIABETES_AND_METABOLISM,
    PEDIATRIC_ENDOCRINOLOGY,
    NEUROENDOCRINOLOGY,
    REPRODUCTIVE_ENDOCRINOLOGY_AND_INFERTILITY,
    SPORTS_ENDOCRINOLOGY,
    GERIATRIC_ENDOCRINOLOGY,
    THYROID_DISORDERS,
    ONCOLOGIC_ENDOCRINOLOGY,
    ADRENAL_DISORDERS,
    GENETIC_ENDOCRINOLOGY
}
